spring.application.name=pharmacy

spring.datasource.url=jdbc:${DB_URL:mysql://localhost:3306/pharmacydb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Niharika@18}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
logging.level.org.springframework.security=DEBUG